name: weathering_willow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SF Compact Display
      fonts: 
        - asset: assets/fonts/SF-Compact-Display-Regular.otf
        # https://github.com/thelioncape/San-Francisco-family/blob/master/SF%20Compact/SF-Compact-Display-Regular.otf